[package]
name = "binary-diff"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "binary-diff"
path = "src/cli.rs"
required-features = ["bin"]


[features]
bin = ["clap"]

[dependencies]
### Logging
log = "0.4.14"
env_logger = "0.9.0"

bcmp = "0.4.1"

clap = { version = "2.33.3", optional = true }